version: "3"
services:
  bot:
    image: rce-bot-vk:latest
    # build:
      # context: ./
      # dockerfile: dockerfile
    environment:
      - JMX_ACCESS_FILE=/app/config/jmxremote.access
      - JMX_PASSWORD_FILE=/app/config/jmxremote.password
      - JMX_HOST=0.0.0.0
      - JMX_PORT=9010
      - LAUNCH_ARGS= |
          -cb 8080

    ports:
      - "80:8080" # HTTP callback port
      - "9010:9010" # RMI
    volumes:
      - "./config:/app/config"

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=136900
      - MYSQL_DATABASE=rce_bot