version: "3"
services:
  bot:
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      - JMX_ACCESS_FILE=/app/config/jmxremote.access
      - JMX_PASSWORD_FILE=/app/config/jmxremote.password
      - JMX_HOST=0.0.0.0
      - JMX_PORT=9010
      - LAUNCH_ARGS= |
          -cb 8080

    ports:
      - "80:8080" # HTTP callback port
      - "443:8080" # HTTPS callback port
      - "9010:9010" # RMI
    volumes:
      - "./config:/app/config"
