name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  java_version: 8

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: "${{ env.java_version }}"
        distribution: "temurin"
        cache: maven
    - name: Build with Maven
      run: mvn clean test


  build:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: "${{ env.java_version }}"
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests -Dmaven.test.skip=true
      
    - name: Archive .jar artifact
      uses: actions/upload-artifact@v3
      with:
        name: rce-bot-vk_jar
        path: target/*.jar

  Docker:
    needs: [build]
    uses: ./.github/workflows/docker-image.yml

  Deploy:
      needs: [Docker]
      uses: ./.github/workflows/deploy.yml
