name: deploy
on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: rce-bot-vk_docker
          path: ./
          
      - name: Resolve variables in configs
        env:
          JMX_USERNAME: ${{ secrets.JMX_USERNAME }}
          JMX_PASSWORD: ${{ secrets.JMX_PASSWORD }}
          RCEBOT_GROUP_TOKEN: ${{ secrets.RCEBOT_GROUP_TOKEN }}
          AGROMONITORING_API_KEY: ${{ secrets.AGROMONITORING_API_KEY }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SAUCENAO_USER_ID: ${{ secrets.SAUCENAO_AUTH }}
          SAUCENAO_TOKEN: ${{ secrets.SAUCENAO_TOKEN }}
          SAUCENAO_AUTH: ${{ secrets.SAUCENAO_USER_ID }}
        run: |
          envsubst < config/bot.ini > config/bot.ini.tmp
          envsubst < config/jmxremote.access > config/jmxremote.access.tmp
          envsubst < config/jmxremote.password > config/jmxremote.password.tmp
          
          mv config/bot.ini.tmp config/bot.ini
          mv config/jmxremote.access.tmp config/jmxremote.access
          mv config/jmxremote.password.tmp config/jmxremote.password
          cat config/*

      - name: Copy files to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "rce-bot-vk_docker.tar.gz,docker-compose.yml,config/*"
          target: "./bot_deploy/"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ls -lah ./bot_deploy/
            chmod 600 ./bot_deploy/config/*
            docker load < ./bot_deploy/rce-bot-vk_docker.tar.gz
          # cd ./bot_deploy/; docker-compose up -d #uncomment on ready to deploy
