name: deploy
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: rce-bot-vk_docker
          path: ./

      - name: Map secrets to environment
        run: |
          echo JMX_USERNAME=${{ secrets.JMX_USERNAME }} >> $GITHUB_ENV
          echo JMX_PASSWORD=${{ secrets.JMX_PASSWORD }} >> $GITHUB_ENV
          echo RCEBOT_GROUP_TOKEN=${{ secrets.RCEBOT_GROUP_TOKEN }} >> $GITHUB_ENV
          echo AGROMONITORING_API_KEY=${{ secrets.AGROMONITORING_API_KEY }} >> $GITHUB_ENV
          echo OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }} >> $GITHUB_ENV
          echo SAUCENAO_USER_ID=${{ secrets.SAUCENAO_AUTH }} >> $GITHUB_ENV
          echo SAUCENAO_TOKEN=${{ secrets.SAUCENAO_TOKEN }} >> $GITHUB_ENV
          echo SAUCENAO_AUTH=${{ secrets.SAUCENAO_USER_ID }} >> $GITHUB_ENV
          
      - name: Resolve variables in configs
        run: |
          envsubst < config/bot.ini > config/bot.ini
          envsubst < config/jmxremote.access > config/bot.ini
          envsubst < config/jmxremote.password > config/bot.ini
          cat config/*

      - name: Copy files to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "rce-bot-vk_docker.tar.gz,config/*"
          target: "./bot_deploy/"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ls -lah ./bot_deploy/
            docker load ./bot_deploy/rce-bot-vk_docker.tar.gz
